baseURL = 'http://127.0.0.1:1313/'
languageCode = 'fr-FR'
title = "Evil Twin : Cyprien's Archives"
theme = 'temple'
DefaultContentLanguage = "fr"
timeout = '360s'
#defaultContentLanguageInSubdir = true
#sectionPagesMenu = 'main'
[Taxonomies]
[imaging.exif]
    includeFields = ".*"

[languages]
 [languages.fr]
#    contentDir = 'content/fr'
    disabled = false
    languageCode = 'fr-FR'
    languageDirection = 'ltr'
    languageName = 'Français'
    title = "Evil Twin : Cyprien's Archives (Fr)"
    weight = 1
 [languages.en]
#    contentDir = 'content/en'
    disabled = false
    languageCode = 'en-US'
    languageDirection = 'ltr'
    languageName = 'English'
    title = "Evil Twin : Cyprien's Archives (En)"
    weight = 2
 [languages.it]
#    contentDir = 'content/it'
    disabled = false
    languageCode = 'it-IT'
    languageDirection = 'ltr'
    languageName = 'Italian'
    title = "Evil Twin : Cyprien's Archives (It)"
    weight = 3

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
#    [markup.goldmark.renderHooks]
#      [markup.goldmark.renderHooks.link]
#        enableDefault = true
[markup.goldmark.renderHooks.image]
enableDefault = true

[markup.goldmark.renderHooks.link]
enableDefault = true
    [markup.goldmark.parser]
     wrapStandAloneImageWithinParagraph = false
      [markup.goldmark.parser.attribute]
        block = true
        title = true
      
[menus]
#  [[menus.main]]
#     name = 'Medias'
#     url = '/page/gallery/'
#     weight = 3
#     [menus.main.params]
#       rel = 'external'
  [[menus.main]]
    name = 'Discord'
    url = 'https://discord.gg/rvRYEtbJ5x'
    weight = 7
    [menus.main.params]
      rel = 'external'

[params.repository]
  branch = 'main'
  owner = 'zap-le-simple'
  repo = 'evil-twin-archives'
  service = 'GitHub'
  urlPatternEdit = 'https://github.com/%s/%s/edit/%s/%s'
  urlPatternView = 'https://github.com/%s/%s/blob/%s/%s'